return {
    ['C Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['G Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['D Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['A Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['E Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['B Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['F# Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['C# Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['F Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['Bb Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['Eb Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['Ab Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['Db Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['Gb Maj'] = ':lua require("dictator").key_constructor()<CR>',
    ['Cb Maj'] = ':lua require("dictator").key_constructor()<CR>',

    ['a min'] = ':lua require("dictator").key_constructor()<CR>',
    ['e min'] = ':lua require("dictator").key_constructor()<CR>',
    ['b min'] = ':lua require("dictator").key_constructor()<CR>',
    ['f# min'] = ':lua require("dictator").key_constructor()<CR>',
    ['c# min'] = ':lua require("dictator").key_constructor()<CR>',
    ['g# min'] = ':lua require("dictator").key_constructor()<CR>',
    ['d# min'] = ':lua require("dictator").key_constructor()<CR>',
    ['a# min'] = ':lua require("dictator").key_constructor()<CR>',
    ['d min'] = ':lua require("dictator").key_constructor()<CR>',
    ['g min'] = ':lua require("dictator").key_constructor()<CR>',
    ['c min'] = ':lua require("dictator").key_constructor()<CR>',
    ['f min'] = ':lua require("dictator").key_constructor()<CR>',
    ['bb min'] = ':lua require("dictator").key_constructor()<CR>',
    ['eb min'] = ':lua require("dictator").key_constructor()<CR>',
    ['ab min'] = ':lua require("dictator").key_constructor()<CR>',
}
